name: CI/CD workflow
on: workflow_dispatch
jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python
        run: |
          python python.py
      
  test_model:
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test model accuracy
        run: |
          python -c "from python import evaluate_model; evaluate_model()"

  deploy_model:
    runs-on: ubuntu-latest
    needs: test_model
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy model
        run: |
          echo "Deploying the model"     